---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(cluster)
library(tidyverse)

```

```{r}
all <- read_csv("all.csv")
```


```{r}
my_df <- all %>%
  select(`User-ID`,`Book-Title`,`Book-Rating`) %>%
  filter(`Book-Rating` > 0) 

my_df <- my_df[sample(nrow(my_df), 5000), ]
rm(all)
```


```{r}
my_df <- my_df %>%
  rename(title = `Book-Title`, rating = `Book-Rating`, user = `User-ID`) %>%
  pivot_wider(names_from = title, values_from = rating)
```

```{r}
my_df.scaled <- daisy(my_df)
```


```{r}
my_df.hc <- hclust(my_df.scaled)
plot(my_df.hc)
groups <- cutree(my_df.hc, k=3) 
rect.hclust(my_df.hc, k=3, border="red")
```

```{r}
my_df %>%
  mutate(cluster = groups) %>%
  select(user, cluster)
```

```{r}
my_df %>%
  mutate(cluster = groups) %>%
  select(user, cluster) %>%
  group_by(cluster) %>%
  summarize(n = n())
```

```{r}
my_df_wide <- my_df %>%
  mutate(cluster = groups) %>%
  pivot_longer(2:ncol(my_df), names_to="books") 
  
```

```{r}
my_df_wide %>%
  filter(cluster == 1) %>%
  filter(!is.na(value)) %>%
  group_by(books) %>%
  summarize(n = n()) %>%
  arrange(desc(n))
```

```{r}
my_df_wide %>%
  filter(cluster == 2) %>%
  filter(!is.na(value)) %>%
  group_by(books) %>%
  summarize(n = n()) %>%
  arrange(desc(n))
```
